<div align="center">

# 🧹 Xử lý dữ liệu (Data Preprocessing)

</div>

### Import thư viện 📦

In [1]:

# Import các thư viện cần thiết
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

### Định nghĩa hàm sử dụng ⚙️

In [2]:

# Load dữ liệu từ file .csv
df = pd.read_csv(r"C:\học Python\Data Science and Atifficial Interligent\Các project data science và AI\Data Analsys\Phân tích dữ liệu và xây dựng hybrid model trong việc dự đoán volatility của Bitcoin tại thi trường crypto toàn cầu\data\Bitcoin_time_series_raw.csv")
df.drop(columns='Unnamed: 0',inplace=True)
df

,timestamp,open,high,low,close,volume,ATR,BB_width_norm,RSI,MACD_Hist,MA20,EMA20,Date,CFGI,BTC Dominance,Total CMC,USDTD,Bitcoin CMC,volatility_14_annual
0,2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,315.640000,NaN,NaN,0.000000,NaN,13529.010000,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
1,2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,316.381068,NaN,0.000000,-1.201493,NaN,13527.654699,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
2,2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,315.799756,NaN,-0.116553,-1.911172,NaN,13526.833598,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
3,2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,315.832221,NaN,-0.190124,-2.312652,NaN,13526.347928,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
4,2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,315.745026,NaN,-0.367052,-2.002172,NaN,13526.658373,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71661,2026-03-10 23:00:00,69721.58,69981.80,69698.46,69948.63,1165.159140,630.619773,0.125565,22715.462812,798.079696,67678.468042,68793.166000,2026-03-10,13.0,59.352780,2.357494e+12,7.801736,1.399238e+12,0.613922
71662,2026-03-11 00:00:00,69948.64,70173.25,69759.63,70044.87,728.929610,629.331941,0.125669,15875.054066,799.139303,67685.964667,68798.370590,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.613833
71663,2026-03-11 01:00:00,70044.87,70144.00,69880.00,70071.26,947.248790,627.163799,0.125801,14663.557223,800.221240,67692.641000,68803.663270,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.599838
71664,2026-03-11 02:00:00,70071.26,70119.59,69614.00,69810.72,1612.875480,626.442292,0.125898,61217.518220,800.267129,67698.840000,68807.850616,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.600167
71665,2026-03-11 03:00:00,69810.73,69887.11,69669.88,69735.51,217.647290,624.013733,0.125992,757700.798537,799.979867,67704.578750,68811.707827,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.598911

In [3]:
df.head()

,timestamp,open,high,low,close,volume,ATR,BB_width_norm,RSI,MACD_Hist,MA20,EMA20,Date,CFGI,BTC Dominance,Total CMC,USDTD,Bitcoin CMC,volatility_14_annual
0,2018-01-01 00:00:00,13715.65,13715.65,13400.01,13529.01,443.356199,315.640000,NaN,NaN,0.000000,NaN,13529.010000,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
1,2018-01-01 01:00:00,13528.99,13595.89,13155.38,13203.06,383.697006,316.381068,NaN,0.000000,-1.201493,NaN,13527.654699,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
2,2018-01-01 02:00:00,13203.00,13418.43,13200.00,13330.18,429.064572,315.799756,NaN,-0.116553,-1.911172,NaN,13526.833598,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
3,2018-01-01 03:00:00,13330.26,13611.27,13290.00,13410.03,420.087030,315.832221,NaN,-0.190124,-2.312652,NaN,13526.347928,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN
4,2018-01-01 04:00:00,13434.98,13623.29,13322.15,13601.01,340.807329,315.745026,NaN,-0.367052,-2.002172,NaN,13526.658373,2018-01-01,NaN,41.779461,5.354920e+11,0.257424,2.237257e+11,NaN

In [4]:
df.tail()

,timestamp,open,high,low,close,volume,ATR,BB_width_norm,RSI,MACD_Hist,MA20,EMA20,Date,CFGI,BTC Dominance,Total CMC,USDTD,Bitcoin CMC,volatility_14_annual
71661,2026-03-10 23:00:00,69721.58,69981.80,69698.46,69948.63,1165.15914,630.619773,0.125565,22715.462812,798.079696,67678.468042,68793.166000,2026-03-10,13.0,59.352780,2.357494e+12,7.801736,1.399238e+12,0.613922
71662,2026-03-11 00:00:00,69948.64,70173.25,69759.63,70044.87,728.92961,629.331941,0.125669,15875.054066,799.139303,67685.964667,68798.370590,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.613833
71663,2026-03-11 01:00:00,70044.87,70144.00,69880.00,70071.26,947.24879,627.163799,0.125801,14663.557223,800.221240,67692.641000,68803.663270,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.599838
71664,2026-03-11 02:00:00,70071.26,70119.59,69614.00,69810.72,1612.87548,626.442292,0.125898,61217.518220,800.267129,67698.840000,68807.850616,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.600167
71665,2026-03-11 03:00:00,69810.73,69887.11,69669.88,69735.51,217.64729,624.013733,0.125992,757700.798537,799.979867,67704.578750,68811.707827,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.598911

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71666 entries, 0 to 71665
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             71666 non-null  object
 1   open                  71666 non-null  float64
 2   high                  71666 non-null  float64
 3   low                   71666 non-null  float64
 4   close                 71666 non-null  float64
 5   volume                71666 non-null  float64
 6   ATR                   71666 non-null  float64
 7   BB_width_norm         71187 non-null  float64
 8   RSI                   71665 non-null  float64
 9   MACD_Hist             71666 non-null  float64
 10  MA20                  71187 non-null  float64
 11  EMA20                 71666 non-null  float64
 12  Date                  71666 non-null  object
 13  CFGI                  70827 non-null  float64
 14  BTC Dominance         71666 non-null  float64
 15  Total CMC             71666 non-null  float64
 16  USDTD                 71666 non-null  float64
 17  Bitcoin CMC           71666 non-null  float64
 18  volatility_14_annual  71330 non-null  float64
dtypes: float64(17), object(2)
memory usage: 10.4+ MB

In [6]:

# Lấy ra các cột có giá trị null
null_columns = df.columns[df.isnull().any()].to_list()
null_columns

['BB_width_norm', 'RSI', 'MA20', 'CFGI', 'volatility_14_annual']

In [7]:

# lấy ra tổng null của các cột
df_totla_null = df.isnull().sum().reset_index()
df_totla_null.rename(columns={0:'total null'},inplace=True)
df_totla_null

                   index  total null
0              timestamp           0
1                   open           0
2                   high           0
3                    low           0
4                  close           0
5                 volume           0
6                    ATR           0
7          BB_width_norm         479
8                    RSI           1
9              MACD_Hist           0
10                  MA20         479
11                 EMA20           0
12                  Date           0
13                  CFGI         839
14         BTC Dominance           0
15             Total CMC           0
16                 USDTD           0
17           Bitcoin CMC           0
18  volatility_14_annual         336

In [8]:

# xóa đi các giá trị null
df = df.dropna()

In [9]:

# Lấy ra các cột có giá trị null
null_columns = df.columns[df.isnull().any()].to_list()
null_columns

[]

In [10]:

# kiểm tra các giá trị trùng lặp
total_duplicate = df.duplicated().sum()
total_duplicate

np.int64(0)

In [11]:
df['timestamp'].dtype

dtype('O')

In [12]:

# chuyển đổi kiểu dữ liệu timestampe từ object sang datetime64(ns)
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70827 entries, 743 to 71665
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             70827 non-null  datetime64[ns]
 1   open                  70827 non-null  float64
 2   high                  70827 non-null  float64
 3   low                   70827 non-null  float64
 4   close                 70827 non-null  float64
 5   volume                70827 non-null  float64
 6   ATR                   70827 non-null  float64
 7   BB_width_norm         70827 non-null  float64
 8   RSI                   70827 non-null  float64
 9   MACD_Hist             70827 non-null  float64
 10  MA20                  70827 non-null  float64
 11  EMA20                 70827 non-null  float64
 12  Date                  70827 non-null  object
 13  CFGI                  70827 non-null  float64
 14  BTC Dominance         70827 non-null  float64
 15  Total CMC             70827 non-null  float64
 16  USDTD                 70827 non-null  float64
 17  Bitcoin CMC           70827 non-null  float64
 18  volatility_14_annual  70827 non-null  float64
dtypes: datetime64[ns](1), float64(17), object(1)
memory usage: 10.8+ MB

In [14]:

# Xuất dữ liệu sang file csv
# df.to_csv('Bitcoin_time_series_processed.csv')